<a href="https://colab.research.google.com/github/Elwing-Chou/tibame20260804/blob/main/tibame20260901.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import urllib.request as req
import bs4 as bs

url = "https://tabelog.com/tw/tokyo/rstLst/sweets/?SrtT=rt"
resp = req.urlopen(url)
content = resp.read()
html = bs.BeautifulSoup(content)
rs = html.find_all("div", {"class":"list-rst__body"})
for r in rs:
    # 評價/晚價/午價/例假日
    name = r.find("a", {"class":"list-rst__rst-name-target"})
    area_genre = r.find("div", {"class":"list-rst__area-genre"})
    rating = r.find("span", {"class":"c-rating__val"})
    prices = r.find_all("span", {"class":"c-rating-v3__val"})
    lunch_price = prices[1]
    dinner_price = prices[0]
    holiday = r.find("span", {"class":"list-rst__holiday-text"})

    name_text = name.get_text().strip()
    name_href = name["href"]
    area_genre_text = area_genre.get_text().strip()
    rating_text = rating.get_text().strip()
    lunch_price_text = lunch_price.get_text().strip()
    dinner_price_text = dinner_price.get_text().strip()
    holiday_text = holiday.get_text().strip()

    print(rating_text)
    print(name_text)
    print(name_href)
    print(area_genre_text)
    print(lunch_price_text)
    print(dinner_price_text)
    print(holiday_text)
    print("-" * 30)

4.25
Bon.nu
https://tabelog.com/tw/tokyo/A1304/A130401/13184186/
參宮橋車站 356m / 法式料理, 牛排, 蛋糕
JPY 50,000 - JPY 59,999
JPY 50,000 - JPY 59,999
-
------------------------------
4.18
Yama
https://tabelog.com/tw/tokyo/A1316/A131602/13279936/
白金台車站 725m / 甜食
JPY 30,000 - JPY 39,999
JPY 20,000 - JPY 29,999
星期二, 星期三
------------------------------
4.16
Okashiya Ucchi
https://tabelog.com/tw/tokyo/A1309/A130901/13238644/
北參道車站 250m / 蛋糕, 西式甜點
JPY 10,000 - JPY 14,999
-
-
------------------------------
4.05
蒼菓
https://tabelog.com/tw/tokyo/A1307/A130703/13297330/
廣尾車站 702m / 甜食
JPY 15,000 - JPY 19,999
JPY 15,000 - JPY 19,999
星期一, 星期二, 星期日
------------------------------
4.00
ESPRIT C. KEI GINZA
https://tabelog.com/tw/tokyo/A1301/A130101/13296199/
銀座車站 330m / 法式料理, 甜食
-
JPY 30,000 - JPY 39,999
星期一, 星期日
------------------------------
3.95
GELATERIA ACQUOLINA
https://tabelog.com/tw/tokyo/A1317/A131701/13141364/
祐天寺車站 45m / 意式冰淇淋/冰淇淋, 軟冰淇淋
- JPY 999
-
星期一, 星期二
------------------------------
3.89
Patisserie Ryoko
https://tabelog.com/tw/tokyo/A1316/A131603/13137010/
高輪台車站 423m / 蛋糕, 泡芙, 西式甜點
- JPY 999
-
星期一, 星期二, 星期三, 星期四
------------------------------
3.88
a tes souhaits!
https://tabelog.com/tw/tokyo/A1320/A132001/13005853/
西荻窪車站 992m / 蛋糕, 甜食
- JPY 999
- JPY 999
星期一, 星期二
------------------------------
3.88
AIGRE DOUCE
https://tabelog.com/tw/tokyo/A1305/A130502/13005641/
目白車站 562m / 蛋糕, 馬卡龍
JPY 1,000 - JPY 1,999
JPY 1,000 - JPY 1,999
星期一, 星期二
------------------------------
3.88
Frederic Cassel 銀座三越店
https://tabelog.com/tw/tokyo/A1301/A130101/13116839/
銀座車站 176m / 蛋糕, 甜食, 巧克力
JPY 2,000 - JPY 2,999
-
-
------------------------------
3.87
patisserie Paris S'eveille
https://tabelog.com/tw/tokyo/A1317/A131703/13005198/
自由丘車站 212m / 蛋糕, 咖啡店, 麵包
JPY 1,000 - JPY 1,999
JPY 1,000 - JPY 1,999
-
------------------------------
3.87
CHOCOLATIER PALET D’OR 東京
https://tabelog.com/tw/tokyo/A1302/A130201/13038473/
二重橋前車站 351m / 巧克力, 咖啡店, 蛋糕
JPY 2,000 - JPY 2,999
JPY 2,000 - JPY 2,999
-
------------------------------
3.87
Think
https://tabelog.com/tw/tokyo/A1311/A131105/13283557/
鶯谷車站 643m / 麵包, 西式甜點
-
JPY 1,000 - JPY 1,999
星期一, 星期二, 星期三
------------------------------
3.86
Usagiya
https://tabelog.com/tw/tokyo/A1311/A131101/13003599/
湯島車站 195m / 日式點心, 銅鑼燒
- JPY 999
- JPY 999
星期三
------------------------------
3.86
Avranches Guesnay
https://tabelog.com/tw/tokyo/A1310/A131004/13186450/
春日車站 30m / 蛋糕, 巧克力
JPY 1,000 - JPY 1,999
JPY 1,000 - JPY 1,999
星期一, 星期二
------------------------------
3.86
GAZTA
https://tabelog.com/tw/tokyo/A1316/A131602/13223261/
白金高輪車站 271m / 蛋糕
JPY 1,000 - JPY 1,999
-
星期一
------------------------------
3.86
Boulangerie Sudo
https://tabelog.com/tw/tokyo/A1317/A131709/13098861/
松陰神社前車站 34m / 麵包, 咖啡店, 甜食
- JPY 999
- JPY 999
星期一, 星期二, 星期三, 星期四
------------------------------
3.86
patisserie K.ViNCENT
https://tabelog.com/tw/tokyo/A1309/A130905/13035194/
飯田橋車站 408m / 蛋糕, 巧克力, 西式甜點
-
JPY 10,000 - JPY 14,999
-
------------------------------
3.85
VIRON 丸之內店
https://tabelog.com/tw/tokyo/A1302/A130201/13043904/
東京車站 320m / 麵包, 蛋糕, 咖啡店
JPY 1,000 - JPY 1,999
JPY 1,000 - JPY 1,999
-
------------------------------
3.85
日本橋 長門
https://tabelog.com/tw/tokyo/A1302/A130202/13011481/
日本橋車站 292m / 日式點心
JPY 1,000 - JPY 1,999
JPY 1,000 - JPY 1,999
星期日, 節假日
------------------------------

In [2]:
import urllib.request as req
import bs4 as bs

def download_page(page):
    url = f"https://tabelog.com/tw/tokyo/rstLst/sweets/{page}/?SrtT=rt"
    resp = req.urlopen(url)
    content = resp.read()
    html = bs.BeautifulSoup(content)
    rs = html.find_all("div", {"class":"list-rst__body"})
    # !!!
    result = []
    for r in rs:
        # 評價/晚價/午價/例假日
        name = r.find("a", {"class":"list-rst__rst-name-target"})
        area_genre = r.find("div", {"class":"list-rst__area-genre"})
        rating = r.find("span", {"class":"c-rating__val"})
        prices = r.find_all("span", {"class":"c-rating-v3__val"})
        lunch_price = prices[1]
        dinner_price = prices[0]
        holiday = r.find("span", {"class":"list-rst__holiday-text"})

        name_text = name.get_text().strip()
        name_href = name["href"]
        area_genre_text = area_genre.get_text().strip()
        rating_text = rating.get_text().strip()
        lunch_price_text = lunch_price.get_text().strip()
        dinner_price_text = dinner_price.get_text().strip()
        holiday_text = holiday.get_text().strip()
        # !
        data = {
            "rating":rating_text,
            "name":name_text,
            "link":name_href,
            "area_genre":area_genre_text,
            "price_lunch":lunch_price_text,
            "price_dinner":dinner_price_text,
            "holiday":holiday_text,
        }
        result.append(data)
    return result

download_page(2)

[{'rating': '3.85',
  'name': 'Au Bon Vieux Temps 尾山台店',
  'link': 'https://tabelog.com/tw/tokyo/A1317/A131715/13181654/',
  'area_genre': '尾山台車站 368m / 蛋糕, 小菜, 咖啡店',
  'price_lunch': 'JPY 1,000 - JPY 1,999',
  'price_dinner': 'JPY 1,000 - JPY 1,999',
  'holiday': '星期二, 星期三'},
 {'rating': '3.85',
  'name': 'Ryoura',
  'link': 'https://tabelog.com/tw/tokyo/A1317/A131707/13188208/',
  'area_genre': '用賀車站 290m / 蛋糕, 西式甜點',
  'price_lunch': '-',
  'price_dinner': 'JPY 3,000 - JPY 3,999',
  'holiday': '星期二, 星期三'},
 {'rating': '3.85',
  'name': 'Minimal 富ヶ谷本店',
  'link': 'https://tabelog.com/tw/tokyo/A1303/A130301/13175834/',
  'area_genre': '代代木八幡車站 372m / 巧克力, 蛋糕, 咖啡店',
  'price_lunch': 'JPY 1,000 - JPY 1,999',
  'price_dinner': 'JPY 1,000 - JPY 1,999',
  'holiday': '-'},
 {'rating': '3.85',
  'name': "L'AUTOMNE 中野店",
  'link': 'https://tabelog.com/tw/tokyo/A1321/A132101/13118933/',
  'area_genre': '新江古田車站 39m / 蛋糕, 咖啡店, 麵包',
  'price_lunch': 'JPY 1,000 - JPY 1,999',
  'price_dinner': 'JPY 1,000 - JPY 1,999',
  'holiday': '星期一, 星期二'},
 {'rating': '3.84',
  'name': 'Curry Spice Gelateria KALPASI',
  'link': 'https://tabelog.com/tw/tokyo/A1318/A131802/13247887/',
  'area_genre': '下北澤車站 105m / 咖喱, 意式冰淇淋/冰淇淋, 亞洲料理, 民族料理',
  'price_lunch': 'JPY 1,000 - JPY 1,999',
  'price_dinner': 'JPY 1,000 - JPY 1,999',
  'holiday': '星期四'},
 {'rating': '3.84',
  'name': 'ASTERISQUE',
  'link': 'https://tabelog.com/tw/tokyo/A1318/A131811/13140735/',
  'area_genre': '代代木上原車站 172m / 蛋糕',
  'price_lunch': '- JPY 999',
  'price_dinner': '- JPY 999',
  'holiday': '星期一, 星期二'},
 {'rating': '3.84',
  'name': '法國菓子 甜點師 巧克力師 Inamurashōzō',
  'link': 'https://tabelog.com/tw/tokyo/A1311/A131105/13047298/',
  'area_genre': '日暮里車站 139m / 蛋糕, 巧克力',
  'price_lunch': 'JPY 1,000 - JPY 1,999',
  'price_dinner': 'JPY 1,000 - JPY 1,999',
  'holiday': '星期一, 星期二'},
 {'rating': '3.84',
  'name': 'La Maison du Chocolat 丸之內店',
  'link': 'https://tabelog.com/tw/tokyo/A1301/A130102/13000036/',
  'area_genre': '有樂町車站 180m / 巧克力, 蛋糕, 咖啡店',
  'price_lunch': 'JPY 3,000 - JPY 3,999',
  'price_dinner': '-',
  'holiday': '-'},
 {'rating': '3.84',
  'name': 'TORAYA TOKYO',
  'link': 'https://tabelog.com/tw/tokyo/A1302/A130201/13147493/',
  'area_genre': '東京車站 128m / 咖啡店, 日式點心, 刨冰',
  'price_lunch': 'JPY 1,000 - JPY 1,999',
  'price_dinner': '-',
  'holiday': '-'},
 {'rating': '3.84',
  'name': 'Premarché Gelateria 東京中目黑站前店',
  'link': 'https://tabelog.com/tw/tokyo/A1317/A131701/13223646/',
  'area_genre': '中目黑車站 120m / 意式冰淇淋/冰淇淋',
  'price_lunch': '- JPY 999',
  'price_dinner': '- JPY 999',
  'holiday': '星期四'},
 {'rating': '3.84',
  'name': '一幸庵',
  'link': 'https://tabelog.com/tw/tokyo/A1323/A132302/13005076/',
  'area_genre': '茗荷谷車站 207m / 日式點心',
  'price_lunch': '- JPY 999',
  'price_dinner': '-',
  'holiday': '星期一, 星期二, 星期日'},
 {'rating': '3.84',
  'name': 'Creperie Tirol',
  'link': 'https://tabelog.com/tw/tokyo/A1318/A131814/13205650/',
  'area_genre': '祖師谷大藏車站 271m / 可麗餅/法式薄餅',
  'price_lunch': 'JPY 1,000 - JPY 1,999',
  'price_dinner': '-',
  'holiday': '星期一, 星期四'},
 {'rating': '3.84',
  'name': 'LESS by Gabriele Riva & Kanako Sakakura',
  'link': 'https://tabelog.com/tw/tokyo/A1303/A130302/13274859/',
  'area_genre': '惠比壽車站 521m / 蛋糕, 巧克力',
  'price_lunch': 'JPY 2,000 - JPY 2,999',
  'price_dinner': '-',
  'holiday': '星期三'},
 {'rating': '3.83',
  'name': 'VIRON 澀谷店',
  'link': 'https://tabelog.com/tw/tokyo/A1303/A130301/13004626/',
  'area_genre': '澀谷車站 465m / 麵包, 三明治, 蛋糕',
  'price_lunch': '- JPY 999',
  'price_dinner': '- JPY 999',
  'holiday': '-'},
 {'rating': '3.83',
  'name': 'PATISSERIE ASAKO IWAYANAGI',
  'link': 'https://tabelog.com/tw/tokyo/A1317/A131715/13189509/',
  'area_genre': '等等力車站 232m / 蛋糕, 咖啡店',
  'price_lunch': '-',
  'price_dinner': 'JPY 1,000 - JPY 1,999',
  'holiday': '星期一, 星期二'},
 {'rating': '3.83',
  'name': '和光Tea Salon',
  'link': 'https://tabelog.com/tw/tokyo/A1301/A130101/13009081/',
  'area_genre': '銀座車站 53m / 咖啡店, 蛋糕',
  'price_lunch': 'JPY 4,000 - JPY 4,999',
  'price_dinner': 'JPY 4,000 - JPY 4,999',
  'holiday': '-'},
 {'rating': '3.83',
  'name': 'Patisserie Yu Sasage',
  'link': 'https://tabelog.com/tw/tokyo/A1318/A131809/13155662/',
  'area_genre': '千歲烏山車站 273m / 蛋糕, 麵包',
  'price_lunch': '- JPY 999',
  'price_dinner': '-',
  'holiday': '星期二, 星期三'},
 {'rating': '3.83',
  'name': 'Shizuka西式點心店 自然點心研究所 銀座5丁目店',
  'link': 'https://tabelog.com/tw/tokyo/A1301/A130101/13270326/',
  'area_genre': '銀座車站 122m / 西式甜點',
  'price_lunch': '-',
  'price_dinner': 'JPY 1,000 - JPY 1,999',
  'holiday': '-'},
 {'rating': '3.82',
  'name': "Nata de Cristiano's",
  'link': 'https://tabelog.com/tw/tokyo/A1318/A131810/13153384/',
  'area_genre': '代代木公園車站 185m / 甜食, 麵包, 蛋糕',
  'price_lunch': '- JPY 999',
  'price_dinner': '- JPY 999',
  'holiday': '-'},
 {'rating': '3.82',
  'name': 'Patisserie TRES CALME',
  'link': 'https://tabelog.com/tw/tokyo/A1323/A132301/13175122/',
  'area_genre': '千石車站 235m / 蛋糕, 馬卡龍, 麵包',
  'price_lunch': 'JPY 1,000 - JPY 1,999',
  'price_dinner': '-',
  'holiday': '星期一'}]

- 迴圈SOP
    - 走過(list): for in list/str
    - 固定次數: for i in range(次) i=0...次-1
    - 不固定次數: while True+break

In [3]:
import pandas as pd
total = []
for i in range(10):
    page = i + 1
    result_json = download_page(page)
    result_df = pd.DataFrame(result_json)
    total.append(result_df)

df = pd.concat(total)
# if you need
df = df.reset_index(drop=True)
df

,rating,name,link,area_genre,price_lunch,price_dinner,holiday
0,4.25,Bon.nu,https://tabelog.com/tw/tokyo/A1304/A130401/131...,"參宮橋車站 356m / 法式料理, 牛排, 蛋糕","JPY 50,000 - JPY 59,999","JPY 50,000 - JPY 59,999",-
1,4.18,Yama,https://tabelog.com/tw/tokyo/A1316/A131602/132...,白金台車站 725m / 甜食,"JPY 30,000 - JPY 39,999","JPY 20,000 - JPY 29,999","星期二, 星期三"
2,4.16,Okashiya Ucchi,https://tabelog.com/tw/tokyo/A1309/A130901/132...,"北參道車站 250m / 蛋糕, 西式甜點","JPY 10,000 - JPY 14,999",-,-
3,4.05,蒼菓,https://tabelog.com/tw/tokyo/A1307/A130703/132...,廣尾車站 702m / 甜食,"JPY 15,000 - JPY 19,999","JPY 15,000 - JPY 19,999","星期一, 星期二, 星期日"
4,4.00,ESPRIT C. KEI GINZA,https://tabelog.com/tw/tokyo/A1301/A130101/132...,"銀座車站 330m / 法式料理, 甜食",-,"JPY 30,000 - JPY 39,999","星期一, 星期日"
...,...,...,...,...,...,...,...
195,3.72,羽二重團子 本店,https://tabelog.com/tw/tokyo/A1311/A131105/130...,"日暮里車站 318m / 日式點心, 日式甜點店",- JPY 999,- JPY 999,-
196,3.72,赤坂青野 本店,https://tabelog.com/tw/tokyo/A1308/A130801/130...,赤坂車站 511m / 日式點心,- JPY 999,- JPY 999,"星期日, 節假日"
197,3.72,Sumida珈琲,https://tabelog.com/tw/tokyo/A1312/A131201/131...,"錦糸町車站 541m / 咖啡店, 咖啡館, 蛋糕","JPY 1,000 - JPY 1,999","JPY 1,000 - JPY 1,999","星期六, 星期日, 節假日"
198,3.72,Irie,https://tabelog.com/tw/tokyo/A1313/A131303/130...,"門前仲町車站 104m / 日式甜點店, 刨冰","JPY 1,000 - JPY 1,999","JPY 1,000 - JPY 1,999",星期三
199,3.72,菊丸,https://tabelog.com/tw/tokyo/A1311/A131102/130...,"田原町車站 278m / 日式甜點店, 刨冰, 咖啡店",- JPY 999,- JPY 999,星期一

- pandas兩大操作
    - 過濾: 準備資料筆數依樣多的True/False帶入
    - 轉換: Series.apply(錦囊)
        - Series: 1D, 一行或者一列

- Everything is an object
    - 任何東西都有型態, 每種型態都有他的操作
    - 字典型態 操作[key]
    - 我之前都說 功能後面一定得加小括號
    - 現在我會說 不一定要加小括號
        - 功能型態: print 操作: (3)

In [13]:
def func(i):
    return i * 3

df["rating"].astype(float).apply(func)

0      12.75
1      12.54
2      12.48
3      12.15
4      12.00
       ...
195    11.16
196    11.16
197    11.16
198    11.16
199    11.16
Name: rating, Length: 200, dtype: float64

In [16]:
def func(i):
    spl = i.split(" / ")
    ans = {
        "area":None,
        "genre":None
    }
    if len(spl) == 2:
        ans["area"] = spl[0]
        ans["genre"] = spl[1]
    elif len(spl) == 1:
        ans["genre"] = spl[1]
    return pd.Series(ans)

df[["area", "genre"]] = df["area_genre"].apply(func)
df

,rating,name,link,area_genre,price_lunch,price_dinner,holiday,area,genre
0,4.25,Bon.nu,https://tabelog.com/tw/tokyo/A1304/A130401/131...,"參宮橋車站 356m / 法式料理, 牛排, 蛋糕","JPY 50,000 - JPY 59,999","JPY 50,000 - JPY 59,999",-,參宮橋車站 356m,"法式料理, 牛排, 蛋糕"
1,4.18,Yama,https://tabelog.com/tw/tokyo/A1316/A131602/132...,白金台車站 725m / 甜食,"JPY 30,000 - JPY 39,999","JPY 20,000 - JPY 29,999","星期二, 星期三",白金台車站 725m,甜食
2,4.16,Okashiya Ucchi,https://tabelog.com/tw/tokyo/A1309/A130901/132...,"北參道車站 250m / 蛋糕, 西式甜點","JPY 10,000 - JPY 14,999",-,-,北參道車站 250m,"蛋糕, 西式甜點"
3,4.05,蒼菓,https://tabelog.com/tw/tokyo/A1307/A130703/132...,廣尾車站 702m / 甜食,"JPY 15,000 - JPY 19,999","JPY 15,000 - JPY 19,999","星期一, 星期二, 星期日",廣尾車站 702m,甜食
4,4.00,ESPRIT C. KEI GINZA,https://tabelog.com/tw/tokyo/A1301/A130101/132...,"銀座車站 330m / 法式料理, 甜食",-,"JPY 30,000 - JPY 39,999","星期一, 星期日",銀座車站 330m,"法式料理, 甜食"
...,...,...,...,...,...,...,...,...,...
195,3.72,羽二重團子 本店,https://tabelog.com/tw/tokyo/A1311/A131105/130...,"日暮里車站 318m / 日式點心, 日式甜點店",- JPY 999,- JPY 999,-,日暮里車站 318m,"日式點心, 日式甜點店"
196,3.72,赤坂青野 本店,https://tabelog.com/tw/tokyo/A1308/A130801/130...,赤坂車站 511m / 日式點心,- JPY 999,- JPY 999,"星期日, 節假日",赤坂車站 511m,日式點心
197,3.72,Sumida珈琲,https://tabelog.com/tw/tokyo/A1312/A131201/131...,"錦糸町車站 541m / 咖啡店, 咖啡館, 蛋糕","JPY 1,000 - JPY 1,999","JPY 1,000 - JPY 1,999","星期六, 星期日, 節假日",錦糸町車站 541m,"咖啡店, 咖啡館, 蛋糕"
198,3.72,Irie,https://tabelog.com/tw/tokyo/A1313/A131303/130...,"門前仲町車站 104m / 日式甜點店, 刨冰","JPY 1,000 - JPY 1,999","JPY 1,000 - JPY 1,999",星期三,門前仲町車站 104m,"日式甜點店, 刨冰"
199,3.72,菊丸,https://tabelog.com/tw/tokyo/A1311/A131102/130...,"田原町車站 278m / 日式甜點店, 刨冰, 咖啡店",- JPY 999,- JPY 999,星期一,田原町車站 278m,"日式甜點店, 刨冰, 咖啡店"

In [23]:
tags = [
    "星期一",
    "星期二",
    "星期三",
    "星期四",
    "星期五",
    "星期六",
    "星期日"
]
def func(i):
    ans = {}
    for t in tags:
        if t in i:
            ans[t] = "N"
        else:
            ans[t] = "Y"
    return pd.Series(ans)


df[tags] = df["holiday"].apply(func)
fil = df["星期一"] == "Y"
df[fil]

,rating,name,link,area_genre,price_lunch,price_dinner,holiday,area,genre,星期一,星期二,星期三,星期四,星期五,星期六,星期日
0,4.25,Bon.nu,https://tabelog.com/tw/tokyo/A1304/A130401/131...,"參宮橋車站 356m / 法式料理, 牛排, 蛋糕","JPY 50,000 - JPY 59,999","JPY 50,000 - JPY 59,999",-,參宮橋車站 356m,"法式料理, 牛排, 蛋糕",Y,Y,Y,Y,Y,Y,Y
1,4.18,Yama,https://tabelog.com/tw/tokyo/A1316/A131602/132...,白金台車站 725m / 甜食,"JPY 30,000 - JPY 39,999","JPY 20,000 - JPY 29,999","星期二, 星期三",白金台車站 725m,甜食,Y,N,N,Y,Y,Y,Y
2,4.16,Okashiya Ucchi,https://tabelog.com/tw/tokyo/A1309/A130901/132...,"北參道車站 250m / 蛋糕, 西式甜點","JPY 10,000 - JPY 14,999",-,-,北參道車站 250m,"蛋糕, 西式甜點",Y,Y,Y,Y,Y,Y,Y
9,3.88,Frederic Cassel 銀座三越店,https://tabelog.com/tw/tokyo/A1301/A130101/131...,"銀座車站 176m / 蛋糕, 甜食, 巧克力","JPY 2,000 - JPY 2,999",-,-,銀座車站 176m,"蛋糕, 甜食, 巧克力",Y,Y,Y,Y,Y,Y,Y
10,3.87,patisserie Paris S'eveille,https://tabelog.com/tw/tokyo/A1317/A131703/130...,"自由丘車站 212m / 蛋糕, 咖啡店, 麵包","JPY 1,000 - JPY 1,999","JPY 1,000 - JPY 1,999",-,自由丘車站 212m,"蛋糕, 咖啡店, 麵包",Y,Y,Y,Y,Y,Y,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194,3.72,森乃園,https://tabelog.com/tw/tokyo/A1302/A130204/130...,人形町車站 135m / 軟冰淇淋,"JPY 1,000 - JPY 1,999","JPY 1,000 - JPY 1,999",-,人形町車站 135m,軟冰淇淋,Y,Y,Y,Y,Y,Y,Y
195,3.72,羽二重團子 本店,https://tabelog.com/tw/tokyo/A1311/A131105/130...,"日暮里車站 318m / 日式點心, 日式甜點店",- JPY 999,- JPY 999,-,日暮里車站 318m,"日式點心, 日式甜點店",Y,Y,Y,Y,Y,Y,Y
196,3.72,赤坂青野 本店,https://tabelog.com/tw/tokyo/A1308/A130801/130...,赤坂車站 511m / 日式點心,- JPY 999,- JPY 999,"星期日, 節假日",赤坂車站 511m,日式點心,Y,Y,Y,Y,Y,Y,N
197,3.72,Sumida珈琲,https://tabelog.com/tw/tokyo/A1312/A131201/131...,"錦糸町車站 541m / 咖啡店, 咖啡館, 蛋糕","JPY 1,000 - JPY 1,999","JPY 1,000 - JPY 1,999","星期六, 星期日, 節假日",錦糸町車站 541m,"咖啡店, 咖啡館, 蛋糕",Y,Y,Y,Y,Y,N,N
198,3.72,Irie,https://tabelog.com/tw/tokyo/A1313/A131303/130...,"門前仲町車站 104m / 日式甜點店, 刨冰","JPY 1,000 - JPY 1,999","JPY 1,000 - JPY 1,999",星期三,門前仲町車站 104m,"日式甜點店, 刨冰",Y,Y,N,Y,Y,Y,Y